### ISSUE TITLE
Python visualization dependencies

### ISSUE THREAD

**Issue by ellenhp** [arpruss/tammes#1]
This code looks useful for a ray tracing project I'm working on. I'm hoping to validate the generated output visually before incorporating it, but it seems like the python script is out of date. On the off chance you still have a working virtual environment for this, I was wondering if you could run pip freeze and give post the output? The project seems pretty old so no worries if you don't have a working environment. It shouldn't be too difficult to write a rough visualization. Just wanted to ask in case you still have it :)

**Comment by arpruss** [comment]
Sorry, I don't.

**Comment by ellenhp** [comment]
Sounds good. Thanks for the code though, saved me a lot of time either way :)
